ingresses:
  - https://yrkesskade-melding-mottak.dev.intern.nav.no
inboundApplications:
  - application: yrkesskade-melding-api
  - application: yrkesskade-prosessering
outboundApplications:
  - application: yrkesskade-melding-api
externalHosts:
  - host: saf.dev-fss-pub.nais.io
  - host: pdl-api.dev-fss-pub.nais.io
  - host: oppgave-q1.dev-fss-pub.nais.io
springProfile: dev
tenant: trygdeetaten.no
kafka_pool: nav-dev