ingresses:
  - https://yrkesskade-melding-mottak.dev.intern.nav.no
externalHosts:
  - host: saf.dev-fss-pub.nais.io
  - host: pdl-api.dev-fss-pub.nais.io
  - host: oppgave-q1.dev-fss-pub.nais.io
  - host: dokarkiv.dev-fss-pub.nais.io
springProfile: dev
tenant: trygdeetaten.no
kafka_pool: nav-dev
gcpProjectId: yrkesskade-dev-6235
vedleggBucketName: yrkesskade-skadeforklaring-vedlegg-dev
fss-cluster: dev-fss
