ingresses:
  - https://yrkesskade-melding-mottak.intern.nav.no
externalHosts:
  - host: saf.prod-fss-pub.nais.io
  - host: pdl-api.prod-fss-pub.nais.io
  - host: oppgave.prod-fss-pub.nais.io
  - host: dokarkiv.prod-fss-pub.nais.io
springProfile: prod
tenant: nav.no
kafka_pool: nav-prod