spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
  kafka:
    properties:
      schema.registry.url: denne-maa-bare-ha-en-verdi
  cloud:
    gcp:
      bigquery:
        enabled: false
kafka:
  topic:
    aapen-dok-journalfoering: test
    skademelding-innsendt: yrkesskade.privat-yrkesskade-skademeldinginnsendt

funksjonsbrytere:
  enabled: false
NAIS_CLUSTER_NAME: lokal
KAFKA_BROKERS: ${spring.embedded.kafka.brokers}
GCP_TEAM_PROJECT_ID: stub

no.nav.security.jwt:
  issuer:
    azuread:
      discoveryurl: http://localhost:${mock-oauth2-server.port}/azuread/.well-known/openid-configuration
      accepted_audience: aad-client-id
  client:
    registration:
      saf-maskintilmaskin:
        token-endpoint-url: http://localhost:${mock-oauth2-server.port}/azuread/token
        grant-type: client_credentials
        scope: saf
        authentication:
          client-id: dummy-client-id
          client-secret: dummy-secret
          client-auth-method: client_secret_basic
      pdl-maskintilmaskin:
        token-endpoint-url: http://localhost:${mock-oauth2-server.port}/azuread/token
        grant-type: client_credentials
        scope: pdl
        authentication:
          client-id: dummy-client-id
          client-secret: dummy-secret
          client-auth-method: client_secret_basic
      oppgave-maskintilmaskin:
        token-endpoint-url: http://localhost:${mock-oauth2-server.port}/azuread/token
        grant-type: client_credentials
        scope: oppgave
        authentication:
          client-id: dummy-client-id
          client-secret: dummy-secret
          client-auth-method: client_secret_basic

YRKESSKADE_DOKGEN_API_URL: http://localhost:5914
YRKESSKADE_KODEVERK_API_URL: http://localhost:8080