name: "Build and deploy yrkesskade-melding-mottak"
on:
  push:
    branches:
    - "master"
env:
  "IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}"
jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-18.04"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/cache@v2"
      with:
        "path": "~/.m2/repository"
        "key": "${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}"
        "restore-keys": "${{ runner.os }}-maven-"
    - uses: "actions/setup-java@v1"
      with:
        "java-version": "11"
    - name: "compile and run tests"
      env:
        GITHUB_USERNAME: navikt
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: "mvn install -X --settings .m2/maven-settings.xml --file pom.xml"
#      run: "mvn install -X"
    - name: "Login to GitHub Docker Registry"
      uses: "docker/login-action@v1"
      with:
        "registry": "ghcr.io"
        "username": "${{ github.actor }}"
        "password": "${{ secrets.GITHUB_TOKEN }}"
    - name: "Build and push the Docker image"
      run: "docker build --pull --tag ${IMAGE} . && docker push ${IMAGE}"
  "deployAppToDev":
    name: "Deploy app to dev"
    needs: "build"
    runs-on: "ubuntu-18.04"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Deploy to DEV"
      uses: "nais/deploy/actions/deploy@v1"
      env:
        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
        "CLUSTER": "dev-gcp"
        "RESOURCE": ".nais/nais.yaml"
        "VARS": ".nais/dev.yaml"
  "deployAlertsToDev":
    name: "Deploy alerts to dev"
    needs: "build"
    runs-on: "ubuntu-18.04"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Deploy alerts to DEV"
      uses: "nais/deploy/actions/deploy@v1"
      env:
        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
        "CLUSTER": "dev-gcp"
        "RESOURCE": ".nais/alerts-dev.yaml"
        "VARS": ".nais/dev.yaml"
